logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

spring:
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        prefer-ip-address: true
        register: true
        deregister: true
        health-check-path: /actuator/health
        health-check-interval: 15s
  rabbitmq:
    host: rabbitmq

security:
  oauth2:
    resource:
      user-info-uri: http://auth-service:5000/uaa/users/current